### PR TITLE
Created a "state" service, changed how engine props are serialized.

### PR DESCRIPTION
**Pull request by dacarley**
Also moved logger into the "services" folder and namespace.

### CODE REVIEW

**Comment by topisani** [comment]
This looks nice, i mainly have one request:
This removes the nesting of serialization, but an `EngineDispatcher` needs to have its engines as children in the `state` json, since id like to be able to have multiple `EngineDispatcher` instances, and therefore multiple instances of some engines. This will mainly be useful for FX, where we might have one running on external input and one on the internal audio, and maybe even multiple chained fx, which should be serialized individually. Other than that, i like this interface!

**Comment by dacarley** [comment]
I have some other changes in mind that should address this.

main.cpp will (eventually, after a few more refactorings) become just a series of "service" interactions.  "init", "start", "shutdown", etc.  Much cleaner at the top-level, and keeps the various parts of the system better encapsulated.

Usage of "globals" would be minimized/elminated.  Pretty much everything would eventually be moved into appropriate namespaces/services.

Specific engine instances would be handled (created, initialized, etc) within the engine namespace.  I need to play around with the implementation details a bit before I have a crystal clear plan here though.  Making this change should allow for engine state to be serialized through a hierarchy, rather than each engine serializing itself directly into state.

Let's continue to communicate about the evolution here.

**Comment by topisani** [comment]
Definately agree on simplifying main.cpp, and getting it down to a few service interactions

`otto::globals´ definately needs to go, i like the idea of replacing it with individual services.
 
Engines specifically is an interesting problem, and if we are to write an `EngineManagement` service, these are some of the things we'd need to be aware of:

 1. It should be general enough to allow custom engine layouts (someone might want to hook up multiple FX chained in their layouts)
 1. It should be designed with a `SignalPath` service in mind
 1. It should allow for multiple instances of the same engine, meaning it cannot use types as identifiers.
 1. It needs to be partly populated by what is currently `EngineDispatcher`s instead of engines directly.
 1. There's going to be a lot of lookup, and this is part of the reason why i haven't done this yet. String lookups are not exactly fast (though it might be negible, but we have performance issues already), meaning we should identify the engines using at least a cached hash. Maybe some constexpr stuff could help here?

I like the whole "service" concept, and i suggest the structure becomes this:
  - `util`: Generic, library style utils, could be released separately at some point if they are very useful.
  - `core`: Core classes
  - `engines`: These are the actual features of the OTTO
  - `services`: engine manager,  Audio drivers, UI drivers, signal path description etc

On that list, modules can only depend on those above it.
Also, it gives a nice separation of what you have to edit when you are building your own OTTO:
 - For hardware compatibility, and custom layouts, you write, toggle or edit services only.
 - If you want to add an engine, you should be able to not touch anything outside that engine's own files

**Comment by D-I-S-K-U-S** [comment]
I don’t know much about all this, but the last two arguments topisani had made sense to me. Enginebuilders should not (have to) edit the core of the otto. I think. Modular hardware stuff is also very preferrable.

**Comment by dacarley** [comment]
@topisani Can you explain what you mean by `SignalPath`

I would imagine that the string lookups are not going to be a meaningful part of the performance equation.  There should be be basically nothing in the system that needs to dynamically discover an engine in the midst of a core loop.  That information should always be gathered during an initialization phase of some sort, where the performance impact of lookup is negligible.

**Comment by topisani** [comment]
you are probably right about the strings lookups.

by SignalPath i mean what is currently `mainaudio.cpp`

**Pull request closed without merging**
